-- =================================================================
-- 001. System User 신설 + News 모델 확장 + perspective_logs 신설
-- =================================================================
-- ⚠️ 자동 실행 금지. Ryu 검토 후 수동 실행.
-- 실행 명령: psql $DATABASE_URL -f prisma/migrations-pending/001_*.sql
-- =================================================================

BEGIN;

-- (1) 시스템 작성자 user 신설
-- author_id로 자동 글과 사람 글을 분리 추적
INSERT INTO "User" (id, email, username, name, role, points, "createdAt", "updatedAt")
VALUES (
  'system_user_mavs_kr',
  'system@mavs.kr',
  'mavs_kr_system',
  'MAVS.KR',
  'ADMIN',
  0,
  NOW(),
  NOW()
)
ON CONFLICT (email) DO NOTHING;

-- (2) NewsSource enum에 NBA_API, INJURY_REPORT 추가
ALTER TYPE "NewsSource" ADD VALUE IF NOT EXISTS 'NBA_API';
ALTER TYPE "NewsSource" ADD VALUE IF NOT EXISTS 'INJURY_REPORT';

-- (3) News 모델 자동 콘텐츠 컬럼 확장 (nullable + default)
ALTER TABLE "News"
  ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "sourceId" TEXT,
  ADD COLUMN IF NOT EXISTS "riskLevel" TEXT,
  ADD COLUMN IF NOT EXISTS "perspectiveStatus" TEXT,
  ADD COLUMN IF NOT EXISTS "perspectiveText" TEXT,
  ADD COLUMN IF NOT EXISTS "published" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "retractedAt" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "retractReason" TEXT,
  ADD COLUMN IF NOT EXISTS "team" TEXT;

-- sourceId 중복 방지 unique index (NULL 허용)
CREATE UNIQUE INDEX IF NOT EXISTS "News_sourceId_key"
  ON "News" ("sourceId")
  WHERE "sourceId" IS NOT NULL;

-- 자동 글 조회 인덱스
CREATE INDEX IF NOT EXISTS "News_autoGenerated_publishedAt_idx"
  ON "News" ("autoGenerated", "publishedAt" DESC);

-- (4) perspective_logs 테이블 신설 — 시각 박스 생성 전 단계 감사 로그
CREATE TABLE IF NOT EXISTS "perspective_logs" (
  "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  "newsId" TEXT,
  "sourceUrl" TEXT,
  "riskLevel" TEXT NOT NULL,
  "draft1" TEXT NOT NULL,
  "critique1" TEXT,
  "draft2" TEXT,
  "critique2" TEXT,
  "finalText" TEXT NOT NULL,
  "usedFallback" BOOLEAN NOT NULL DEFAULT FALSE,
  "bannedPatternHit" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "perspective_logs_newsId_idx"
  ON "perspective_logs" ("newsId");

CREATE INDEX IF NOT EXISTS "perspective_logs_createdAt_idx"
  ON "perspective_logs" ("createdAt" DESC);

COMMIT;

-- =================================================================
-- 롤백 (만일에 대비)
-- =================================================================
-- BEGIN;
-- DROP TABLE IF EXISTS "perspective_logs";
-- DROP INDEX IF EXISTS "News_autoGenerated_publishedAt_idx";
-- DROP INDEX IF EXISTS "News_sourceId_key";
-- ALTER TABLE "News"
--   DROP COLUMN IF EXISTS "retractReason",
--   DROP COLUMN IF EXISTS "retractedAt",
--   DROP COLUMN IF EXISTS "published",
--   DROP COLUMN IF EXISTS "perspectiveText",
--   DROP COLUMN IF EXISTS "perspectiveStatus",
--   DROP COLUMN IF EXISTS "riskLevel",
--   DROP COLUMN IF EXISTS "sourceId",
--   DROP COLUMN IF EXISTS "autoGenerated";
-- DELETE FROM "User" WHERE email = 'system@mavs.kr';
-- -- NewsSource enum 값 제거는 Postgres 한계로 어려움 (테이블 재생성 필요)
-- COMMIT;
