import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { createServerActionClient } from '@/lib/supabase-helpers';

const ADMIN_EMAIL = 'mavsdotkr@gmail.com';

export async function GET() {
  if (process.env.NODE_ENV !== 'development') {
    const supabase = await createServerActionClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user || user.email !== ADMIN_EMAIL) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
  }

  const since = new Date(Date.now() - 30 * 24 * 3600 * 1000);
  const posts = await prisma.news.findMany({
    where: { autoGenerated: true, publishedAt: { gte: since } },
    orderBy: { publishedAt: 'desc' },
    select: {
      id: true,
      title: true,
      titleKr: true,
      publishedAt: true,
      source: true,
      riskLevel: true,
      perspectiveStatus: true,
      perspectiveText: true,
      published: true,
      retractedAt: true,
      retractReason: true,
    },
    take: 200,
  });

  return NextResponse.json({ ok: true, count: posts.length, posts });
}
