import { prisma } from '@/lib/db/prisma';

const SYSTEM_AUTHOR_EMAIL = 'system@mavs.kr';

let cachedSystemAuthorId: string | null = null;

export async function getSystemAuthorId(): Promise<string> {
  if (cachedSystemAuthorId) return cachedSystemAuthorId;
  const user = await prisma.user.findUnique({
    where: { email: SYSTEM_AUTHOR_EMAIL },
    select: { id: true },
  });
  if (!user) {
    throw new Error(
      `System author (${SYSTEM_AUTHOR_EMAIL}) not found. Run migration prisma/migrations-pending/001_*.sql first.`,
    );
  }
  cachedSystemAuthorId = user.id;
  return user.id;
}

export type AutoNewsSource = 'nba_api' | 'mavsmoneyball' | 'smokingcuban' | 'espn' | 'injury_report';
export type RiskLevel = 'low' | 'medium' | 'high';
export type PerspectiveStatus = 'passed' | 'fallback' | 'rejected';

export interface PublishAutoNewsInput {
  title: string;
  body: string;
  perspectiveText: string;
  perspectiveStatus: PerspectiveStatus;
  riskLevel: RiskLevel;
  source: AutoNewsSource;
  sourceId: string;
  sourceUrl?: string;
  imageUrl?: string;
  publishedAt?: Date;
}

export interface PublishResult {
  newsId: string;
  skipped: boolean;
  reason?: string;
}

export async function publishAutoNews(input: PublishAutoNewsInput): Promise<PublishResult> {
  const existing = await prisma.news.findFirst({
    where: { sourceId: input.sourceId },
    select: { id: true },
  });
  if (existing) return { newsId: existing.id, skipped: true, reason: 'duplicate source_id' };

  const sourceEnum = mapToNewsSourceEnum(input.source);

  const created = await prisma.news.create({
    data: {
      title: input.title,
      titleKr: input.title,
      content: input.body,
      contentKr: composeFinalBody(input),
      source: sourceEnum,
      sourceUrl: input.sourceUrl ?? '',
      imageUrl: input.imageUrl,
      publishedAt: input.publishedAt ?? new Date(),
      autoGenerated: true,
      sourceId: input.sourceId,
      riskLevel: input.riskLevel,
      perspectiveStatus: input.perspectiveStatus,
      perspectiveText: input.perspectiveText,
    },
    select: { id: true },
  });

  return { newsId: created.id, skipped: false };
}

function mapToNewsSourceEnum(s: AutoNewsSource): 'ESPN' | 'MAVS_MONEYBALL' | 'SMOKING_CUBAN' | 'NBA_API' | 'INJURY_REPORT' {
  switch (s) {
    case 'espn': return 'ESPN';
    case 'mavsmoneyball': return 'MAVS_MONEYBALL';
    case 'smokingcuban': return 'SMOKING_CUBAN';
    case 'nba_api': return 'NBA_API';
    case 'injury_report': return 'INJURY_REPORT';
  }
}

function composeFinalBody(input: PublishAutoNewsInput): string {
  return input.body;
}
