import { prisma } from '@/lib/db/prisma';
import { pingIndexing } from './indexing-ping';

const SYSTEM_AUTHOR_EMAIL = 'system@mavs.kr';
// `||` 사용 의도적: 빈 문자열("")로 설정돼도 기본값으로 폴백 (`??`는 ""를 유효값 취급)
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://mavs.kr';

let cachedSystemAuthorId: string | null = null;

export async function getSystemAuthorId(): Promise<string> {
  if (cachedSystemAuthorId) return cachedSystemAuthorId;
  const user = await prisma.user.findUnique({
    where: { email: SYSTEM_AUTHOR_EMAIL },
    select: { id: true },
  });
  if (!user) {
    throw new Error(
      `System author (${SYSTEM_AUTHOR_EMAIL}) not found. Run migration prisma/migrations-pending/001_*.sql first.`,
    );
  }
  cachedSystemAuthorId = user.id;
  return user.id;
}

export type AutoNewsSource = 'nba_api' | 'mavsmoneyball' | 'smokingcuban' | 'espn' | 'injury_report';
export type RiskLevel = 'low' | 'medium' | 'high';
/**
 * passed: critique 통과, 정상 발행
 * fallback: lint 또는 critique이 경미한 위반 발견 → closing만 fallback 텍스트로 교체 후 발행
 * rejected: critique이 환각/심각 위반 발견 → 발행 skip + 로그만 남김
 */
export type PerspectiveStatus = 'passed' | 'fallback' | 'rejected';
export type TeamTag = 'mavericks' | 'wings';

export interface PublishAutoNewsInput {
  title: string;
  body: string;          // 본문 (HTML)
  summary?: string;      // 메타 description / 검색 결과 요약
  perspectiveText?: string; // (legacy) 시각박스 — 통합형 칼럼에선 closingParagraph로 대체
  perspectiveStatus: PerspectiveStatus;
  riskLevel: RiskLevel;
  source: AutoNewsSource;
  sourceId: string;
  sourceUrl?: string;
  imageUrl?: string;
  publishedAt?: Date;
  team?: TeamTag;
}

export interface PublishResult {
  newsId: string;
  skipped: boolean;
  reason?: string;
}

export async function publishAutoNews(input: PublishAutoNewsInput): Promise<PublishResult> {
  const existing = await prisma.news.findFirst({
    where: { sourceId: input.sourceId },
    select: { id: true },
  });
  if (existing) return { newsId: existing.id, skipped: true, reason: 'duplicate source_id' };

  const sourceEnum = mapToNewsSourceEnum(input.source);

  const created = await prisma.news.create({
    data: {
      title: input.title,
      titleKr: input.title,
      content: input.body,
      contentKr: input.body,
      summary: input.summary,
      summaryKr: input.summary,
      source: sourceEnum,
      sourceUrl: input.sourceUrl ?? '',
      imageUrl: input.imageUrl,
      publishedAt: input.publishedAt ?? new Date(),
      autoGenerated: true,
      sourceId: input.sourceId,
      riskLevel: input.riskLevel,
      perspectiveStatus: input.perspectiveStatus,
      perspectiveText: input.perspectiveText,
      team: input.team ?? 'mavericks',
    },
    select: { id: true },
  });

  // 발행 즉시 검색엔진 ping (fire-and-forget)
  void pingIndexing([`${SITE_URL}/news/${created.id}`]).catch(() => {});

  return { newsId: created.id, skipped: false };
}

function mapToNewsSourceEnum(s: AutoNewsSource): 'ESPN' | 'MAVS_MONEYBALL' | 'SMOKING_CUBAN' | 'NBA_API' | 'INJURY_REPORT' {
  switch (s) {
    case 'espn': return 'ESPN';
    case 'mavsmoneyball': return 'MAVS_MONEYBALL';
    case 'smokingcuban': return 'SMOKING_CUBAN';
    case 'nba_api': return 'NBA_API';
    case 'injury_report': return 'INJURY_REPORT';
  }
}

