import { prisma } from '@/lib/db/prisma';

/**
 * Gemini 가격 (2026-05 기준, USD)
 * - gemini-2.0-flash: input $0.10/M tokens, output $0.40/M tokens
 * - gemini-2.5-flash: input $0.30/M, output $2.50/M (thinking 끄면 절반)
 * 안전하게 평균 사용량으로 추정.
 */
const AVG_INPUT_TOKENS_PER_CALL = 4000;
const AVG_OUTPUT_TOKENS_PER_CALL = 800;
const COST_INPUT_PER_M = 0.10;  // USD
const COST_OUTPUT_PER_M = 0.40; // USD
const USD_TO_KRW = 1400;

export interface StatsRange {
  from: Date;
  to: Date;
  newsPublished: number;
  perspectiveLogs: number;
  fallbackCount: number;
  rejectedCount: number;
  passedCount: number;
  byTeam: Record<string, number>;
  bySource: Record<string, number>;
  estimatedCalls: number;
  estimatedCostUsd: number;
  estimatedCostKrw: number;
}

export async function computeStats(from: Date, to: Date): Promise<StatsRange> {
  const [news, logs] = await Promise.all([
    prisma.news.findMany({
      where: { autoGenerated: true, publishedAt: { gte: from, lte: to } },
      select: { source: true, team: true, perspectiveStatus: true },
    }),
    prisma.perspectiveLog.findMany({
      where: { createdAt: { gte: from, lte: to } },
      select: { id: true, usedFallback: true, draft2: true },
    }),
  ]);

  const byTeam: Record<string, number> = {};
  const bySource: Record<string, number> = {};
  let fallbackCount = 0;
  let rejectedCount = 0;
  let passedCount = 0;
  for (const n of news) {
    byTeam[n.team ?? 'unknown'] = (byTeam[n.team ?? 'unknown'] || 0) + 1;
    bySource[n.source] = (bySource[n.source] || 0) + 1;
    if (n.perspectiveStatus === 'fallback') fallbackCount++;
    if (n.perspectiveStatus === 'rejected') rejectedCount++;
    if (n.perspectiveStatus === 'passed') passedCount++;
  }

  // 호출 수 추정:
  // - generateColumn 1회/글
  // - critique 1회 기본, draft2 있으면 critique 1회 추가 + generate 1회 추가
  let calls = 0;
  for (const log of logs) {
    calls += 1; // generate1
    calls += 1; // critique1
    if (log.draft2) calls += 2; // generate2 + critique2
  }
  // 만약 perspective_logs가 없으면 (자동 글이 마이그레이션 전 발행됐을 때) 글 수 × 2 추정
  if (calls === 0 && news.length > 0) calls = news.length * 2;

  const inputTokens = calls * AVG_INPUT_TOKENS_PER_CALL;
  const outputTokens = calls * AVG_OUTPUT_TOKENS_PER_CALL;
  const costUsd =
    (inputTokens / 1_000_000) * COST_INPUT_PER_M +
    (outputTokens / 1_000_000) * COST_OUTPUT_PER_M;

  return {
    from,
    to,
    newsPublished: news.length,
    perspectiveLogs: logs.length,
    fallbackCount,
    rejectedCount,
    passedCount,
    byTeam,
    bySource,
    estimatedCalls: calls,
    estimatedCostUsd: Number(costUsd.toFixed(4)),
    estimatedCostKrw: Math.round(costUsd * USD_TO_KRW),
  };
}

export async function computeTodayStats(): Promise<StatsRange> {
  const now = new Date();
  const from = new Date(now);
  from.setHours(0, 0, 0, 0);
  return computeStats(from, now);
}

export async function computeLastNDays(n: number): Promise<StatsRange> {
  const to = new Date();
  const from = new Date(to.getTime() - n * 24 * 3600 * 1000);
  return computeStats(from, to);
}
