import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { checkCronAuth, parseDryRun } from '@/lib/auto-content/cron-auth';
import { computeLastNDays } from '@/lib/auto-content/stats';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://mavs.kr';
const RECIPIENT = 'mavsdotkr@gmail.com';
const RESEND_API_KEY = process.env.RESEND_API_KEY;

export async function GET(request: Request) {
  const authErr = checkCronAuth(request);
  if (authErr) return authErr;
  const dry = parseDryRun(request);

  const since = new Date(Date.now() - 24 * 3600 * 1000);
  const posts = await prisma.news.findMany({
    where: {
      autoGenerated: true,
      publishedAt: { gte: since },
    },
    orderBy: { publishedAt: 'desc' },
    select: {
      id: true,
      title: true,
      titleKr: true,
      publishedAt: true,
      source: true,
      riskLevel: true,
      perspectiveStatus: true,
      perspectiveText: true,
    },
  });

  const total = posts.length;
  const bySource: Record<string, number> = {};
  const byRisk: Record<string, number> = { low: 0, medium: 0, high: 0 };
  const byStatus: Record<string, number> = { passed: 0, fallback: 0, rejected: 0 };
  posts.forEach(p => {
    bySource[p.source] = (bySource[p.source] || 0) + 1;
    if (p.riskLevel && p.riskLevel in byRisk) byRisk[p.riskLevel]++;
    if (p.perspectiveStatus && p.perspectiveStatus in byStatus) byStatus[p.perspectiveStatus]++;
  });

  const [stats1, stats7] = await Promise.all([
    computeLastNDays(1),
    computeLastNDays(7),
  ]);

  const subject = `[MAVS.KR 자동발행] ${new Date().toISOString().slice(0, 10)} — ${total}건 발행 (₩${stats1.estimatedCostKrw})`;
  const html = renderHtml(posts, { total, bySource, byRisk, byStatus }, { stats1, stats7 });

  if (dry || !RESEND_API_KEY) {
    return NextResponse.json({
      ok: true,
      dry: dry || !RESEND_API_KEY,
      reason: !RESEND_API_KEY ? 'RESEND_API_KEY missing — skipping email send' : 'dry-run',
      summary: { total, bySource, byRisk, byStatus },
      stats: { day1: stats1, day7: stats7 },
      subject,
      html_preview: html.slice(0, 500),
    });
  }

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'MAVS.KR <noreply@mavs.kr>',
        to: [RECIPIENT],
        subject,
        html,
      }),
    });
    const data = await res.json();
    return NextResponse.json({ ok: res.ok, ...data, summary: { total, bySource, byRisk, byStatus } });
  } catch (e) {
    return NextResponse.json({ ok: false, error: String(e) }, { status: 500 });
  }
}

function renderHtml(
  posts: Array<{ id: string; title: string; titleKr: string | null; riskLevel: string | null; perspectiveStatus: string | null; perspectiveText: string | null }>,
  summary: { total: number; bySource: Record<string, number>; byRisk: Record<string, number>; byStatus: Record<string, number> },
  extra?: { stats1: import('@/lib/auto-content/stats').StatsRange; stats7: import('@/lib/auto-content/stats').StatsRange },
): string {
  const high = posts.filter(p => p.riskLevel === 'high');
  const medium = posts.filter(p => p.riskLevel === 'medium');
  const low = posts.filter(p => p.riskLevel === 'low');

  const sourceLine = Object.entries(summary.bySource).map(([k, v]) => `${k}: ${v}`).join(' · ');
  const riskLine = `low ${summary.byRisk.low} / medium ${summary.byRisk.medium} / high ${summary.byRisk.high}`;
  const statusLine = `passed ${summary.byStatus.passed} / fallback ${summary.byStatus.fallback} / rejected ${summary.byStatus.rejected}`;

  return `
<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,sans-serif;color:#222;max-width:680px;margin:0 auto;padding:20px;">
  <h2 style="border-bottom:2px solid #0066cc;padding-bottom:8px;">MAVS.KR 자동발행 다이제스트</h2>
  <p><strong>총 ${summary.total}건</strong></p>
  <ul style="line-height:1.7;">
    <li>Source: ${sourceLine}</li>
    <li>Risk: ${riskLine}</li>
    <li>Status: ${statusLine}</li>
  </ul>
  ${extra ? `
  <div style="background:#f6f8fa;border-radius:6px;padding:12px 16px;margin:16px 0;">
    <strong>💰 비용/호출 통계</strong>
    <ul style="margin:6px 0 0 0;line-height:1.6;font-size:13px;">
      <li>오늘: ${extra.stats1.estimatedCalls}회 호출, 추정 비용 <strong>₩${extra.stats1.estimatedCostKrw}</strong> ($${extra.stats1.estimatedCostUsd})</li>
      <li>최근 7일: ${extra.stats7.estimatedCalls}회 호출, 추정 비용 <strong>₩${extra.stats7.estimatedCostKrw}</strong> ($${extra.stats7.estimatedCostUsd})</li>
      <li>월 환산(예상): ₩${Math.round(extra.stats7.estimatedCostKrw * 30 / 7)}</li>
    </ul>
  </div>
  ` : ''}
  ${high.length > 0 ? `
  <h3 style="color:#c00;">🚨 HIGH (${high.length}건) — 전문 확인 필요</h3>
  ${high.map(p => `
    <div style="border-left:3px solid #c00;padding-left:10px;margin-bottom:14px;">
      <a href="${SITE_URL}/news/${p.id}" style="font-weight:bold;color:#0066cc;">${p.titleKr ?? p.title}</a>
      <div style="color:#666;font-size:13px;margin:4px 0;">🟦 ${p.perspectiveText ?? ''}</div>
      <a href="${SITE_URL}/admin/auto-posts" style="color:#c00;font-size:13px;">🚩 회수 페이지로</a>
    </div>
  `).join('')}
  ` : ''}
  ${medium.length > 0 ? `
  <h3 style="color:#d60;">⚠️ MEDIUM (${medium.length}건)</h3>
  ${medium.map(p => `
    <div style="margin-bottom:8px;">
      <a href="${SITE_URL}/news/${p.id}" style="color:#0066cc;">${p.titleKr ?? p.title}</a>
      <div style="color:#666;font-size:12px;">🟦 ${p.perspectiveText ?? ''}</div>
    </div>
  `).join('')}
  ` : ''}
  ${low.length > 0 ? `
  <h3 style="color:#080;">✅ LOW (${low.length}건)</h3>
  <ul>${low.map(p => `<li><a href="${SITE_URL}/news/${p.id}">${p.titleKr ?? p.title}</a></li>`).join('')}</ul>
  ` : ''}
  <hr style="margin-top:30px;">
  <p style="color:#999;font-size:12px;">자동 발송 — <a href="${SITE_URL}/admin/auto-posts">전체 대시보드</a></p>
</body></html>`;
}
