import { config } from 'dotenv';
config({ path: '.env.local', override: true });
import { prisma } from '@/lib/db/prisma';

async function main() {
  // News 신규 컬럼 확인
  const news = await prisma.news.findFirst({
    select: { id: true, team: true, autoGenerated: true, sourceId: true, perspectiveStatus: true, published: true },
  });
  console.log('News 신규 컬럼 select OK:', news ? 'row 존재' : 'row 없음(스키마는 OK)');

  // PerspectiveLog 테이블 확인
  const logCount = await prisma.perspectiveLog.count();
  console.log('PerspectiveLog 테이블 OK, count:', logCount);

  // system user 확인
  const sysUser = await prisma.user.findUnique({ where: { email: 'system@mavs.kr' }, select: { id: true, name: true, role: true } });
  console.log('system user:', sysUser ? `${sysUser.id} (${sysUser.name}, ${sysUser.role})` : '없음!');

  console.log('\n✅ 마이그레이션 검증 완료');
}
main().catch(e => { console.error('ERROR:', e.message); process.exit(1); }).finally(() => prisma.$disconnect());
