import { notFound } from 'next/navigation';
import { prisma } from '@/lib/db/prisma';
import { buildNewsArticleSchema } from '@/lib/seo/jsonld';
import type { Metadata } from 'next';

interface Props {
  params: Promise<{ id: string }>;
}

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://mavs.kr';

export const revalidate = 600;

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const article = await prisma.news.findUnique({
    where: { id },
    select: { title: true, titleKr: true, contentKr: true, content: true, imageUrl: true, publishedAt: true },
  });
  if (!article) return { title: '뉴스를 찾을 수 없습니다 | MAVS.KR' };

  const title = article.titleKr ?? article.title;
  const description = (article.contentKr ?? article.content).replace(/<[^>]+>/g, ' ').slice(0, 160).trim();

  return {
    title: `${title} | MAVS.KR`,
    description,
    alternates: { canonical: `${SITE_URL}/news/${id}` },
    openGraph: {
      type: 'article',
      title,
      description,
      url: `${SITE_URL}/news/${id}`,
      images: article.imageUrl ? [article.imageUrl] : undefined,
      publishedTime: article.publishedAt.toISOString(),
      locale: 'ko_KR',
      siteName: 'MAVS.KR',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: article.imageUrl ? [article.imageUrl] : undefined,
    },
  };
}

export default async function NewsArticlePage({ params }: Props) {
  const { id } = await params;
  const article = await prisma.news.findUnique({ where: { id } });
  if (!article) notFound();

  const schema = buildNewsArticleSchema({
    id: article.id,
    title: article.title,
    titleKr: article.titleKr,
    content: article.content,
    contentKr: article.contentKr,
    imageUrl: article.imageUrl,
    publishedAt: article.publishedAt,
    crawledAt: article.crawledAt,
    sourceUrl: article.sourceUrl,
  });

  const displayTitle = article.titleKr ?? article.title;
  const displayBody = article.contentKr ?? article.content;
  const isAuto = (article as { autoGenerated?: boolean }).autoGenerated ?? false;

  return (
    <article className="mx-auto max-w-3xl px-4 py-8">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <header className="mb-6">
        <h1 className="text-3xl font-bold leading-tight">{displayTitle}</h1>
        <div className="mt-3 flex flex-wrap items-center gap-2 text-sm text-slate-400">
          <time dateTime={article.publishedAt.toISOString()}>
            {article.publishedAt.toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' })}
          </time>
          <span>·</span>
          <span>{article.source}</span>
          {isAuto && (
            <span className="ml-2 inline-flex items-center rounded-full bg-blue-500/15 px-2 py-0.5 text-xs text-blue-300">
              🤖 자동 생성
            </span>
          )}
        </div>
      </header>

      {article.imageUrl && (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={article.imageUrl} alt={displayTitle} className="mb-6 w-full rounded-lg" />
      )}

      <div
        className="prose prose-invert max-w-none"
        dangerouslySetInnerHTML={{ __html: displayBody }}
      />

      {article.sourceUrl && (
        <p className="mt-8 text-sm text-slate-500">
          원문 출처:{' '}
          <a href={article.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline">
            {article.sourceUrl}
          </a>
        </p>
      )}

      {isAuto && (
        <p className="mt-4 text-xs text-slate-500">
          ⚙️ 이 글은 MAVS.KR의 시각을 학습한 AI가 작성했습니다.
        </p>
      )}
    </article>
  );
}
