import { notFound } from 'next/navigation';
import { prisma } from '@/lib/db/prisma';
import { buildNewsArticleSchema } from '@/lib/seo/jsonld';
import type { Metadata } from 'next';

interface Props {
  params: Promise<{ id: string }>;
}

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://mavs.kr';

export const revalidate = 600;

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const article = await prisma.news.findUnique({
    where: { id },
    select: {
      title: true,
      titleKr: true,
      contentKr: true,
      content: true,
      summaryKr: true,
      summary: true,
      imageUrl: true,
      publishedAt: true,
    },
  });
  if (!article) return { title: '뉴스를 찾을 수 없습니다 | MAVS.KR' };

  const title = article.titleKr ?? article.title;
  // summaryKr이 있으면 우선 사용 (column metaDescription) — 더 자연스러운 SEO
  const description = (article.summaryKr ?? article.summary ?? (article.contentKr ?? article.content).replace(/<[^>]+>/g, ' ')).slice(0, 160).trim();

  return {
    title: `${title} | MAVS.KR`,
    description,
    alternates: { canonical: `${SITE_URL}/news/${id}` },
    openGraph: {
      type: 'article',
      title,
      description,
      url: `${SITE_URL}/news/${id}`,
      images: article.imageUrl ? [article.imageUrl] : undefined,
      publishedTime: article.publishedAt.toISOString(),
      locale: 'ko_KR',
      siteName: 'MAVS.KR',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: article.imageUrl ? [article.imageUrl] : undefined,
    },
  };
}

export default async function NewsArticlePage({ params }: Props) {
  const { id } = await params;
  const article = await prisma.news.findUnique({ where: { id } });
  if (!article) notFound();

  const schema = buildNewsArticleSchema({
    id: article.id,
    title: article.title,
    titleKr: article.titleKr,
    content: article.content,
    contentKr: article.contentKr,
    summary: article.summary,
    summaryKr: article.summaryKr,
    imageUrl: article.imageUrl,
    publishedAt: article.publishedAt,
    crawledAt: article.crawledAt,
    sourceUrl: article.sourceUrl,
  });

  const displayTitle = article.titleKr ?? article.title;
  const displayBody = article.contentKr ?? article.content;
  const isAuto = (article as { autoGenerated?: boolean }).autoGenerated ?? false;
  const team = (article as { team?: string | null }).team;

  return (
    <article className="mx-auto max-w-3xl px-4 py-8">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <header className="mb-6">
        <h1 className="text-3xl font-bold leading-tight">{displayTitle}</h1>
        <div className="mt-3 flex flex-wrap items-center gap-2 text-sm text-slate-400">
          <time dateTime={article.publishedAt.toISOString()}>
            {article.publishedAt.toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' })}
          </time>
          <span>·</span>
          <span>{article.source}</span>
          {isAuto && (
            <span className="ml-2 inline-flex items-center rounded-full bg-blue-500/15 px-2 py-0.5 text-xs text-blue-300">
              🤖 자동 생성
            </span>
          )}
          {team === 'wings' && (
            <span className="ml-1 inline-flex items-center rounded-full bg-pink-500/15 px-2 py-0.5 text-xs text-pink-300">
              🏐 Wings (WNBA)
            </span>
          )}
          {team === 'mavericks' && isAuto && (
            <span className="ml-1 inline-flex items-center rounded-full bg-indigo-500/15 px-2 py-0.5 text-xs text-indigo-300">
              🏀 Mavericks
            </span>
          )}
        </div>
      </header>

      {article.imageUrl && (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={article.imageUrl} alt={displayTitle} className="mb-6 w-full rounded-lg" />
      )}

      <div
        className="prose prose-invert max-w-none"
        dangerouslySetInnerHTML={{ __html: displayBody }}
      />

      {article.sourceUrl && (
        <footer className="mt-10 border-t border-slate-800 pt-6 text-sm">
          <div className="text-slate-400">원문 출처</div>
          <a href={article.sourceUrl} target="_blank" rel="noopener noreferrer nofollow" className="text-blue-400 hover:underline break-all">
            {article.sourceUrl}
          </a>
        </footer>
      )}

      <div className="mt-6 rounded-md border border-slate-800 bg-slate-900/40 p-4 text-sm text-slate-300">
        📷 더 깊은 분석과 카드뉴스는{' '}
        <a href="https://instagram.com/mavs.kr" target="_blank" rel="noopener noreferrer" className="text-pink-400 hover:underline">
          @mavs.kr 인스타그램
        </a>
        에서 만날 수 있습니다.
      </div>

      {isAuto && (
        <p className="mt-4 text-xs text-slate-500">
          ⚙️ 이 글은 MAVS.KR의 시각을 학습한 AI가 작성했습니다.
        </p>
      )}

      <RelatedNews currentId={article.id} team={team} />
    </article>
  );
}

async function RelatedNews({ currentId, team }: { currentId: string; team: string | null | undefined }) {
  const related = await prisma.news.findMany({
    where: {
      id: { not: currentId },
      autoGenerated: true,
      published: true,
      team: team ?? undefined,
    },
    orderBy: { publishedAt: 'desc' },
    take: 4,
    select: { id: true, titleKr: true, title: true, publishedAt: true, team: true },
  });

  if (related.length === 0) return null;
  return (
    <section className="mt-12 border-t border-slate-800 pt-6">
      <h2 className="text-lg font-semibold text-slate-200 mb-3">관련 글</h2>
      <ul className="space-y-2">
        {related.map(r => (
          <li key={r.id}>
            <a href={`/news/${r.id}`} className="text-blue-400 hover:underline">
              {r.titleKr ?? r.title}
            </a>
            <span className="ml-2 text-xs text-slate-500">{new Date(r.publishedAt).toLocaleDateString('ko-KR')}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}
