import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { createServerActionClient } from '@/lib/supabase-helpers';

const ADMIN_EMAIL = 'mavsdotkr@gmail.com';

interface Context {
  params: Promise<{ id: string }>;
}

export async function POST(request: Request, ctx: Context) {
  const { id } = await ctx.params;

  // Auth
  if (process.env.NODE_ENV !== 'development') {
    const supabase = await createServerActionClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user || user.email !== ADMIN_EMAIL) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
  }

  let body: { reason?: string } = {};
  try {
    body = await request.json();
  } catch {}
  const reason = (body.reason ?? '').trim() || 'no reason given';

  const news = await prisma.news.findUnique({
    where: { id },
    select: { id: true, autoGenerated: true, published: true },
  });
  if (!news) return NextResponse.json({ error: 'not found' }, { status: 404 });
  if (!news.autoGenerated) {
    return NextResponse.json({ error: 'not an auto-generated post' }, { status: 400 });
  }

  await prisma.news.update({
    where: { id },
    data: {
      published: false,
      retractedAt: new Date(),
      retractReason: reason,
    },
  });

  await prisma.perspectiveLog.create({
    data: {
      newsId: id,
      riskLevel: 'retracted',
      draft1: '',
      finalText: `RETRACTED by admin: ${reason}`,
      usedFallback: false,
    },
  }).catch(() => {});

  return NextResponse.json({ ok: true, id, retracted: true, reason });
}
